# Site settings
title: K-721 Portfolio
author:
  name: K-721
  email: your-email@domain.com
description: "Welcome to my Portfolio"

# Build settings
remote_theme: pages-themes/merlot@v0.2.0
plugins:
- jekyll-remote-theme
